"""make_file_id_nullable

Revision ID: a0b6c5c15a1b
Revises: 23c7270b1d79
Create Date: 2026-05-25 21:21:21.444401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0b6c5c15a1b'
down_revision: Union[str, None] = '23c7270b1d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_records', 'file_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('invoice_records_file_id_fkey'), 'invoice_records', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_records', 'invoice_files', ['file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_records', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_records_file_id_fkey'), 'invoice_records', 'invoice_files', ['file_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoice_records', 'file_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
